name: Deploy Python API Docs

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout genkit-python
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: genkit-python

      - name: Install uv
        uses: astral-sh/setup-uv@f943a4db25e985b8772eb7b1897bb69ee3c3abf7 # v5.1.0
        with:
          version: "latest"

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.4.0
        with:
          python-version-file: "genkit-python/.python-version"

      - name: Install dependencies
        working-directory: genkit-python
        run: uv sync --all-extras --dev

      - name: Build Docs
        working-directory: genkit-python
        run: uv run mkdocs build

      - name: Checkout hosting-templates
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: genkit-ai/hosting-templates
          path: hosting-templates

      - name: Copy Docs to hosting-templates
        run: |
          mkdir -p hosting-templates/api-ref/py-public
          cp -R genkit-python/site/* hosting-templates/api-ref/py-public/

      - name: Setup Node.js (for Firebase CLI)
        uses: actions/setup-node@39370e3970a6d050c08000b21d576f6d815de85d # v4.1.0
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        working-directory: hosting-templates
        run: firebase deploy --only hosting:py-prod --project project-kaizen-404017
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
